apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stt-contact-management
  namespace: integration
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend-integration
    kind: ClusterSecretStore
  target:
    name: stt-contact-management
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: contact-management
        property: ADMIN_PASSWORD
    - secretKey: DB_SERVER_NAME
      remoteRef:
        key: contact-management
        property: DB_SERVER_NAME
    - secretKey: DB_PORT
      remoteRef:
        key: contact-management
        property: DB_PORT
    - secretKey: DB_DATABASE_NAME
      remoteRef:
        key: contact-management
        property: DB_DATABASE_NAME
    - secretKey: DB_USERNAME
      remoteRef:
        key: contact-management
        property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: contact-management
        property: DB_PASSWORD
    - secretKey: JNDI_URL
      remoteRef:
        key: contact-management
        property: JNDI_URL
    - secretKey: ES_BOOTSTRAP_URL
      remoteRef:
        key: contact-management
        property: ES_BOOTSTRAP_URL
    - secretKey: ES_USERNAME
      remoteRef:
        key: contact-management
        property: ES_USERNAME
    - secretKey: ES_PASSWORD
      remoteRef:
        key: contact-management
        property: ES_PASSWORD
    - secretKey: ES_TRUSTSTORE_PASSWORD
      remoteRef:
        key: contact-management
        property: ES_TRUSTSTORE_PASSWORD
