resources:
  - deploy.yaml
  - workflow.yaml
images:
  - name: ghcr.io/staillanibm/msr-contact-management
    newTag: 1.1.5
configMapGenerator:
  - name: contact-management-postman-collection
    files:
      - postmanCollection.json
    options:
      disableNameSuffixHash: true
