apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: contact-management-tests
  namespace: integration
  annotations:
    "argocd.argoproj.io/hook": PostSync
spec:
  entrypoint: run-tests
  templates:
    - name: run-tests
      container:
        image: postman/newman:alpine
        command: ["newman", "run", "/tests/postmanCollection.json"]
        env:
          - name: url
            value: https://contact-management-int.sttlab.local/rad/sttContactManagement.api:ContactManagementAPI
          - name: password
            valueFrom:
              secretKeyRef:
                name: stt-contact-management
                key: ADMIN_PASSWORD
        volumeMounts:
          - name: tests-volume
            mountPath: /tests
  volumes:
    - name: tests-volume
      configMap:
        name: contact-management-postman-collection
