apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
data:
  config.hcl: |
    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = 1
    }

    storage "file" {
      path = "/vault/data"
    }

    disable_mlock = true

    api_addr = "https://vault.sttlab.local"

    ui = true
