apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msr-contact-management
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/staillanibm/sttGitOps.git
    targetRevision: main
    path: msr-contact-management/k8s/int
  destination:
    server: https://kubernetes.default.svc
    namespace: integration
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflow-role
  namespace: integration
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]
  - apiGroups: ["argoproj.io"]
    resources: ["workflows"]
    verbs: ["get", "watch", "list", "create", "delete", "patch", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflow-binding
  namespace: integration
subjects:
  - kind: ServiceAccount
    name: default
    namespace: integration
roleRef:
  kind: Role
  name: argo-workflow-role
  apiGroup: rbac.authorization.k8s.io
